In [12]:
# Import libraries
import pandas as pd
import numpy as np
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path.cwd().parent / 'src'))

from feature_engineering import (
    create_temporal_features,
    create_location_features,
    create_severity_features,
    create_vehicle_features,   # <-- IMPORTANT
    engineer_all_features      # <-- for section 6
)
from config import PROCESSED_DATA_DIR

pd.set_option('display.max_columns', None)

## 1. Load Cleaned Integrated Data

In [13]:
# TODO: Load cleaned integrated data
# %%
# Path to post-integration cleaned dataset
cleaned_path = PROCESSED_DATA_DIR / "integrated_cleaned.parquet"

# Load dataset
df_cleaned = pd.read_parquet(cleaned_path)
print("Cleaned integrated dataset shape:", df_cleaned.shape)
df_cleaned.head()

Cleaned integrated dataset shape: (200000, 22)

,crash_date,crash_time,on_street_name,off_street_name,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,contributing_factor_vehicle_1,contributing_factor_vehicle_2,collision_id,vehicle_type_code1,vehicle_type_code2,borough,zip_code,latitude,longitude,location
0,2019-11-01,09:25:00,PARSONS BOULEVARD,85 AVENUE,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4233299,Sedan,Station Wagon/Sport Utility Vehicle,None,None,40.712223,-73.80650,"{'human_address': None, 'latitude': '40.712223..."
1,2016-10-06,11:40:00,AVENUE O,EAST 10 STREET,0,0,0,0,0,0,0,0,Following Too Closely,Unspecified,3535160,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,BROOKLYN,11230,40.612430,-73.96386,"{'human_address': None, 'latitude': '40.61243'..."
2,2016-07-11,08:30:00,EAST 125 STREET,1 AVENUE,0,0,0,0,0,0,0,0,Unspecified,Unspecified,3479651,Flat Bed,4 dr sedan,None,None,40.801754,-73.93121,"{'human_address': None, 'latitude': '40.801754..."
3,2017-10-02,00:00:00,BORDEN AVENUE,HAMILTON PLACE,1,0,0,0,0,0,1,0,Passenger Distraction,Unspecified,3763990,Sedan,Sedan,QUEENS,11378,40.726160,-73.90012,"{'human_address': None, 'latitude': '40.72616'..."
4,2020-03-16,13:30:00,WEST 37 STREET,None,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4301217,Sedan,Pick-up Truck,None,None,40.755290,-73.99493,"{'human_address': None, 'latitude': '40.75529'..."

## 2. Create Temporal Features

In [14]:
# TODO: Extract time-based features
# %%
# Extract time-based features (hour, day, month, year, day_of_week)
df_temporal = create_temporal_features(df_cleaned)
df_temporal.head()

,crash_date,crash_time,on_street_name,off_street_name,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,contributing_factor_vehicle_1,contributing_factor_vehicle_2,collision_id,vehicle_type_code1,vehicle_type_code2,borough,zip_code,latitude,longitude,location,crash_year,crash_month,crash_day,crash_day_of_week,is_weekend,crash_hour
0,2019-11-01,09:25:00,PARSONS BOULEVARD,85 AVENUE,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4233299,Sedan,Station Wagon/Sport Utility Vehicle,None,None,40.712223,-73.80650,"{'human_address': None, 'latitude': '40.712223...",2019,11,1,4,0,NaN
1,2016-10-06,11:40:00,AVENUE O,EAST 10 STREET,0,0,0,0,0,0,0,0,Following Too Closely,Unspecified,3535160,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,BROOKLYN,11230,40.612430,-73.96386,"{'human_address': None, 'latitude': '40.61243'...",2016,10,6,3,0,NaN
2,2016-07-11,08:30:00,EAST 125 STREET,1 AVENUE,0,0,0,0,0,0,0,0,Unspecified,Unspecified,3479651,Flat Bed,4 dr sedan,None,None,40.801754,-73.93121,"{'human_address': None, 'latitude': '40.801754...",2016,7,11,0,0,NaN
3,2017-10-02,00:00:00,BORDEN AVENUE,HAMILTON PLACE,1,0,0,0,0,0,1,0,Passenger Distraction,Unspecified,3763990,Sedan,Sedan,QUEENS,11378,40.726160,-73.90012,"{'human_address': None, 'latitude': '40.72616'...",2017,10,2,0,0,NaN
4,2020-03-16,13:30:00,WEST 37 STREET,None,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4301217,Sedan,Pick-up Truck,None,None,40.755290,-73.99493,"{'human_address': None, 'latitude': '40.75529'...",2020,3,16,0,0,NaN

## 3. Create Location Features

In [15]:
# TODO: Create location-based features
# %%
# Extract location-based features (borough, zip code, lat/lon bins)
df_location = create_location_features(df_temporal)
df_location.head()

,crash_date,crash_time,on_street_name,off_street_name,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,contributing_factor_vehicle_1,contributing_factor_vehicle_2,collision_id,vehicle_type_code1,vehicle_type_code2,borough,zip_code,latitude,longitude,location,crash_year,crash_month,crash_day,crash_day_of_week,is_weekend,crash_hour,lat_bin,lon_bin
0,2019-11-01,09:25:00,PARSONS BOULEVARD,85 AVENUE,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4233299,Sedan,Station Wagon/Sport Utility Vehicle,NONE,None,40.712223,-73.80650,"{'human_address': None, 'latitude': '40.712223...",2019,11,1,4,0,NaN,3,8
1,2016-10-06,11:40:00,AVENUE O,EAST 10 STREET,0,0,0,0,0,0,0,0,Following Too Closely,Unspecified,3535160,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,BROOKLYN,11230,40.612430,-73.96386,"{'human_address': None, 'latitude': '40.61243'...",2016,10,6,3,0,NaN,1,7
2,2016-07-11,08:30:00,EAST 125 STREET,1 AVENUE,0,0,0,0,0,0,0,0,Unspecified,Unspecified,3479651,Flat Bed,4 dr sedan,NONE,None,40.801754,-73.93121,"{'human_address': None, 'latitude': '40.801754...",2016,7,11,0,0,NaN,4,7
3,2017-10-02,00:00:00,BORDEN AVENUE,HAMILTON PLACE,1,0,0,0,0,0,1,0,Passenger Distraction,Unspecified,3763990,Sedan,Sedan,QUEENS,11378,40.726160,-73.90012,"{'human_address': None, 'latitude': '40.72616'...",2017,10,2,0,0,NaN,3,8
4,2020-03-16,13:30:00,WEST 37 STREET,None,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4301217,Sedan,Pick-up Truck,NONE,None,40.755290,-73.99493,"{'human_address': None, 'latitude': '40.75529'...",2020,3,16,0,0,NaN,4,7

## 4. Create Severity Features

In [16]:
# TODO: Build severity indicators
# %%
# Create severity indicators (total injuries, fatalities, severity score)
df_severity = create_severity_features(df_location)
df_severity.head()

,crash_date,crash_time,on_street_name,off_street_name,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,contributing_factor_vehicle_1,contributing_factor_vehicle_2,collision_id,vehicle_type_code1,vehicle_type_code2,borough,zip_code,latitude,longitude,location,crash_year,crash_month,crash_day,crash_day_of_week,is_weekend,crash_hour,lat_bin,lon_bin,total_injured,total_killed,severity_score
0,2019-11-01,09:25:00,PARSONS BOULEVARD,85 AVENUE,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4233299,Sedan,Station Wagon/Sport Utility Vehicle,NONE,None,40.712223,-73.80650,"{'human_address': None, 'latitude': '40.712223...",2019,11,1,4,0,NaN,3,8,0,0,0
1,2016-10-06,11:40:00,AVENUE O,EAST 10 STREET,0,0,0,0,0,0,0,0,Following Too Closely,Unspecified,3535160,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,BROOKLYN,11230,40.612430,-73.96386,"{'human_address': None, 'latitude': '40.61243'...",2016,10,6,3,0,NaN,1,7,0,0,0
2,2016-07-11,08:30:00,EAST 125 STREET,1 AVENUE,0,0,0,0,0,0,0,0,Unspecified,Unspecified,3479651,Flat Bed,4 dr sedan,NONE,None,40.801754,-73.93121,"{'human_address': None, 'latitude': '40.801754...",2016,7,11,0,0,NaN,4,7,0,0,0
3,2017-10-02,00:00:00,BORDEN AVENUE,HAMILTON PLACE,1,0,0,0,0,0,1,0,Passenger Distraction,Unspecified,3763990,Sedan,Sedan,QUEENS,11378,40.726160,-73.90012,"{'human_address': None, 'latitude': '40.72616'...",2017,10,2,0,0,NaN,3,8,2,0,2
4,2020-03-16,13:30:00,WEST 37 STREET,None,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4301217,Sedan,Pick-up Truck,NONE,None,40.755290,-73.99493,"{'human_address': None, 'latitude': '40.75529'...",2020,3,16,0,0,NaN,4,7,0,0,0

## 5. Create Vehicle Features

In [17]:
# %%
# Create vehicle-related features if needed
df_features = create_vehicle_features(df_severity)
df_features.head()

,crash_date,crash_time,on_street_name,off_street_name,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,contributing_factor_vehicle_1,contributing_factor_vehicle_2,collision_id,vehicle_type_code1,vehicle_type_code2,borough,zip_code,latitude,longitude,location,crash_year,crash_month,crash_day,crash_day_of_week,is_weekend,crash_hour,lat_bin,lon_bin,total_injured,total_killed,severity_score,num_vehicle_types,has_truck,has_bus,has_bicycle
0,2019-11-01,09:25:00,PARSONS BOULEVARD,85 AVENUE,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4233299,SEDAN,STATION WAGON/SPORT UTILITY VEHICLE,NONE,None,40.712223,-73.80650,"{'human_address': None, 'latitude': '40.712223...",2019,11,1,4,0,NaN,3,8,0,0,0,2,0,0,0
1,2016-10-06,11:40:00,AVENUE O,EAST 10 STREET,0,0,0,0,0,0,0,0,Following Too Closely,Unspecified,3535160,STATION WAGON/SPORT UTILITY VEHICLE,STATION WAGON/SPORT UTILITY VEHICLE,BROOKLYN,11230,40.612430,-73.96386,"{'human_address': None, 'latitude': '40.61243'...",2016,10,6,3,0,NaN,1,7,0,0,0,2,0,0,0
2,2016-07-11,08:30:00,EAST 125 STREET,1 AVENUE,0,0,0,0,0,0,0,0,Unspecified,Unspecified,3479651,FLAT BED,4 DR SEDAN,NONE,None,40.801754,-73.93121,"{'human_address': None, 'latitude': '40.801754...",2016,7,11,0,0,NaN,4,7,0,0,0,2,0,0,0
3,2017-10-02,00:00:00,BORDEN AVENUE,HAMILTON PLACE,1,0,0,0,0,0,1,0,Passenger Distraction,Unspecified,3763990,SEDAN,SEDAN,QUEENS,11378,40.726160,-73.90012,"{'human_address': None, 'latitude': '40.72616'...",2017,10,2,0,0,NaN,3,8,2,0,2,2,0,0,0
4,2020-03-16,13:30:00,WEST 37 STREET,None,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4301217,SEDAN,PICK-UP TRUCK,NONE,None,40.755290,-73.99493,"{'human_address': None, 'latitude': '40.75529'...",2020,3,16,0,0,NaN,4,7,0,0,0,2,1,0,0

## 6. Apply All Feature Engineering

In [18]:
# %%
# Apply all feature engineering in one function
df_final = engineer_all_features(df_cleaned)
print("Final dataset with all features shape:", df_final.shape)
df_final.head()

Final dataset with all features shape: (200000, 37)

,crash_date,crash_time,on_street_name,off_street_name,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,contributing_factor_vehicle_1,contributing_factor_vehicle_2,collision_id,vehicle_type_code1,vehicle_type_code2,borough,zip_code,latitude,longitude,location,crash_year,crash_month,crash_day,crash_day_of_week,is_weekend,crash_hour,lat_bin,lon_bin,total_injured,total_killed,severity_score,num_vehicle_types,has_truck,has_bus,has_bicycle
0,2019-11-01,09:25:00,PARSONS BOULEVARD,85 AVENUE,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4233299,SEDAN,STATION WAGON/SPORT UTILITY VEHICLE,NONE,None,40.712223,-73.80650,"{'human_address': None, 'latitude': '40.712223...",2019,11,1,4,0,NaN,3,8,0,0,0,2,0,0,0
1,2016-10-06,11:40:00,AVENUE O,EAST 10 STREET,0,0,0,0,0,0,0,0,Following Too Closely,Unspecified,3535160,STATION WAGON/SPORT UTILITY VEHICLE,STATION WAGON/SPORT UTILITY VEHICLE,BROOKLYN,11230,40.612430,-73.96386,"{'human_address': None, 'latitude': '40.61243'...",2016,10,6,3,0,NaN,1,7,0,0,0,2,0,0,0
2,2016-07-11,08:30:00,EAST 125 STREET,1 AVENUE,0,0,0,0,0,0,0,0,Unspecified,Unspecified,3479651,FLAT BED,4 DR SEDAN,NONE,None,40.801754,-73.93121,"{'human_address': None, 'latitude': '40.801754...",2016,7,11,0,0,NaN,4,7,0,0,0,2,0,0,0
3,2017-10-02,00:00:00,BORDEN AVENUE,HAMILTON PLACE,1,0,0,0,0,0,1,0,Passenger Distraction,Unspecified,3763990,SEDAN,SEDAN,QUEENS,11378,40.726160,-73.90012,"{'human_address': None, 'latitude': '40.72616'...",2017,10,2,0,0,NaN,3,8,2,0,2,2,0,0,0
4,2020-03-16,13:30:00,WEST 37 STREET,None,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4301217,SEDAN,PICK-UP TRUCK,NONE,None,40.755290,-73.99493,"{'human_address': None, 'latitude': '40.75529'...",2020,3,16,0,0,NaN,4,7,0,0,0,2,1,0,0

## 7. Save Final Dataset for Dashboard

In [19]:
# TODO: Save to data/processed/dashboard_data.parquet
# %%
# Save final dataset to be used in dashboard/visual analysis
output_path = PROCESSED_DATA_DIR / "dashboard_data.parquet"
df_final.to_parquet(output_path, index=False)
print(f"Final dataset with features saved to: {output_path}")

Final dataset with features saved to: /Users/omarhatem/Desktop/DataEngineering_ML1/data/processed/dashboard_data.parquet